name: Scenario Probes

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Validate requirements
        run: python scripts/validate_requirements.py
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: scripts/run_tests.sh
      - name: Run scenario probes
        run: python scripts/verify_scenarios.py
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scenes-artifacts
          path: scenes_artifacts
